# Generated by Django 5.1.1 on 2024-11-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_testimonial_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('live stream', 'Live Stream'), ('video/photography', 'Video/Photography'), ('Event Planning', 'Event Planning'), ('Graphic Designing', 'Graphic Designing'), ('Gadget Rental', 'Gadget Rental'), ('MC', 'MC')], default='live_stream', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
