# Generated by Django 5.1.1 on 2024-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_gallery_image_gallery_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='packges',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Full', 'Full'), ('Rental', 'Rental')], default='Full1p', max_length=20),
        ),
    ]
